### ISSUE TITLE
Cartocams.com update frequency?

### ISSUE THREAD

**Issue by wmbr** [wvanderp/WebcamMap#23]
I noted that the webcam data shown on https://cartocams.com/ is lagging at least a week behind the current webcams.json data here on github. Is the website just updated less frequently or is there something broken?

**Comment by wvanderp** [comment]
Somebody (me) wanted to get with the times and renamed master to main.

Netlify however did exactly what I told it to do. It always deployed a new version of the site when something is pushed to master.

This was an oversight on my part. Thank you for noticing and thank you even more for notifying me of the problem

**Comment by wvanderp** [comment]
it seems to be working now. thanks for reporting
