### ISSUE TITLE
New webcams missing

### ISSUE THREAD

**Issue by wmbr** [wvanderp/WebcamMap#27]
The map apparently stopped picking up changes around four or five days ago. In particular, the following changes / new webcams are not reflected:
https://overpass-turbo.eu/s/1KBs

**Comment by wvanderp** [comment]
Thanks for notifying me.

I forgot to read the nomination tos, which clearly said you should use a custom user agent. I fixed that part.

The only thing I now need to do is find a tradeoff between failing silently and spamming me every day.

Thanks again
